CREATE TABLE `fw_user_professional` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `user_id` bigint(20) unsigned NOT NULL,
  `total_experience` int(11) DEFAULT 0,
  `education_level` varchar(100) DEFAULT NULL,
  `field_of_study` varchar(255) DEFAULT NULL,
  `institution_name` varchar(255) DEFAULT NULL,
  `graduation_year` int(11) DEFAULT NULL,
  `professional_summary` text DEFAULT NULL,
  `specialized_skills` text DEFAULT NULL,
  `specialized_experience` text DEFAULT NULL,
  `key_projects` text DEFAULT NULL,
  `previous_employers` text DEFAULT NULL,
  `references` text DEFAULT NULL,
  `availability` varchar(50) DEFAULT NULL,
  `travel_willingness` varchar(50) DEFAULT NULL,
  `drivers_license` varchar(10) DEFAULT NULL,
  `red_seal` varchar(50) DEFAULT NULL,
  `provincial_certificate` varchar(255) DEFAULT NULL,
  `union_membership` varchar(255) DEFAULT NULL,
  `equipment_tools` text DEFAULT NULL,
  `whmis` varchar(50) DEFAULT NULL,
  `first_aid` varchar(50) DEFAULT NULL,
  `fall_protection` varchar(50) DEFAULT NULL,
  `confined_space` varchar(50) DEFAULT NULL,
  `lockout_tagout` varchar(50) DEFAULT NULL,
  `other_safety` text DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `user_id` (`user_id`),
  KEY `idx_total_experience` (`total_experience`),
  KEY `idx_education_level` (`education_level`),
  KEY `idx_availability` (`availability`),
  KEY `idx_drivers_license` (`drivers_license`),
  KEY `idx_red_seal` (`red_seal`),
  CONSTRAINT `fk_user_professional_user_id` FOREIGN KEY (`user_id`) REFERENCES `fw_users` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
