/** HR Vision specialty options (multi-select checkboxes) */
export const HR_VISION_SPECIALTIES = [
  'Anesthesiology',
  'Art Therapist',
  'Athletic Therapist',
  'Audiologist',
  'Behaviour Analyst',
  'Cardiology',
  'Cardiology Technologist',
  'Cardiovascular Perfusionist',
  'Child Life Specialist',
  'Chiropodist',
  'Clinical Research Professional',
  'Cytotechnologist',
  'Dental',
  'Dental Assistant',
  'Dental Hygienist',
  'Dental Technologist',
  'Dental Therapist',
  'Denturist',
  'Dermatology',
  'Diagnostic Medical Sonographer',
  'Drama Therapist',
  'Electroneurophysiology Technologist',
  'Emergency Medical Responder',
  'Emergency Medicine',
  'Endocrinology',
  'Environmental Health Officer',
  'Exercise Physiologist',
  'Family Medicine',
  'Gastroenterology',
  'General Surgery',
  'Genetic Counsellor',
  'Geriatric Medicine',
  'Health Information Management Professional',
  'Hearing Instrument Specialist',
  'Hematology',
  'Histotechnologist',
  'Infectious Disease',
  'Internal Medicine',
  'Kinesiologist',
  'Lactation Consultant',
  'Magnetic Resonance Imaging Technologist',
  'Massage Therapist',
  'Medical Device Reprocessing Technician',
  'Medical Genetics',
  'Medical Laboratory Assistant',
  'Medical Laboratory Technologist',
  'Music Therapist',
  'Nephrology',
  'Neurology',
  'Nuclear Medicine',
  'Nuclear Medicine Technologist',
  'Nutritionist (regulated in some jurisdictions)',
  'Obstetrics and Gynecology',
  'Occupational Medicine',
  'Occupational Therapist',
  'Operating Department Practitioner',
  'Ophthalmic Medical Technologist',
  'Ophthalmology',
  'Optician',
  'Orthopedic Surgery',
  'Orthoptist',
  'Orthotist',
  'Orthotist-Prosthetist',
  'Otolaryngology',
  'Paramedic',
  "Pathologists' Assistant",
  'Pathology',
  'Pediatrics',
  'Pedorthist',
  'Pharmacist',
  'Pharmacy',
  'Pharmacy Technician',
  'Physical Medicine and Rehabilitation',
  'Physiotherapist',
  'Plastic Surgery',
  'Podiatrist',
  'Preventive Medicine',
  'Prosthetist',
  'Psychiatry',
  'Psychological Associate',
  'Psychologist',
  'Psychotherapist',
  'Pulmonary Function Technologist',
  'Pulmonology',
  'Radiation Therapist',
  'Radiologic Technologist',
  'Radiology',
  'Recreation Therapist',
  'Registered Dietitian',
  'Respiratory Therapist',
  'Rheumatology',
  'Social Worker',
  'Speech-Language Pathologist',
  'Thoracic Surgery',
  'Urology',
] as const

export type HrVisionSpecialty = (typeof HR_VISION_SPECIALTIES)[number]

export const HR_VISION_SPECIALTY_SET = new Set<string>(HR_VISION_SPECIALTIES)

export function isHrVisionSpecialty(value: string): value is HrVisionSpecialty {
  return HR_VISION_SPECIALTY_SET.has(value)
}
