/**
 * Canadian FSA (first 3 characters of postal code) catalog for Locations of interest.
 */

export interface PostalFsaLocation {
  code: string
  city: string
}

export const POSTAL_FSA_LOCATIONS: PostalFsaLocation[] = [
  { code: 'K0A', city: 'Ottawa' },
  { code: 'K0B', city: 'Rockland' },
  { code: 'K0C', city: 'Cornwall' },
  { code: 'K0E', city: 'Brockville' },
  { code: 'K0G', city: 'Kemptville' },
  { code: 'K0H', city: 'Kingston' },
  { code: 'K0J', city: 'Ottawa' },
  { code: 'K0K', city: 'Belleville' },
  { code: 'K0L', city: 'Peterborough' },
  { code: 'K0M', city: 'Lindsay' },
  { code: 'K1A', city: 'Nepean' },
  { code: 'K1B', city: 'Ottawa' },
  { code: 'K1C', city: 'Gloucester' },
  { code: 'K1E', city: 'Gloucester' },
  { code: 'K1G', city: 'Ottawa' },
  { code: 'K1H', city: 'Ottawa' },
  { code: 'K1J', city: 'Ottawa' },
  { code: 'K1K', city: 'Vanier' },
  { code: 'K1L', city: 'Vanier' },
  { code: 'K1M', city: 'Ottawa' },
  { code: 'K1N', city: 'Ottawa' },
  { code: 'K1P', city: 'Ottawa' },
  { code: 'K1R', city: 'Ottawa' },
  { code: 'K1S', city: 'Ottawa' },
  { code: 'K1T', city: 'Ottawa' },
  { code: 'K1V', city: 'Ottawa' },
  { code: 'K1W', city: 'Gloucester' },
  { code: 'K1X', city: 'Gloucester' },
  { code: 'K1Y', city: 'Ottawa' },
  { code: 'K1Z', city: 'Ottawa' },
  { code: 'K2A', city: 'Ottawa' },
  { code: 'K2B', city: 'Nepean' },
  { code: 'K2C', city: 'Nepean' },
  { code: 'K2E', city: 'Nepean' },
  { code: 'K2G', city: 'Nepean' },
  { code: 'K2H', city: 'Nepean' },
  { code: 'K2J', city: 'Nepean' },
  { code: 'K2K', city: 'Nepean' },
  { code: 'K2L', city: 'Nepean' },
  { code: 'K2M', city: 'Kanata' },
  { code: 'K2P', city: 'Ottawa' },
  { code: 'K2R', city: 'Nepean' },
  { code: 'K2S', city: 'Ottawa' },
  { code: 'K2T', city: 'Kanata' },
  { code: 'K2V', city: 'Kanata' },
  { code: 'K2W', city: 'Kanata' },
  { code: 'K4A', city: 'Gloucester' },
  { code: 'K4B', city: 'Gloucester' },
  { code: 'K4C', city: 'Cumberland' },
  { code: 'K4K', city: 'Clarence-Rockland' },
  { code: 'K4M', city: 'Ottawa' },
  { code: 'K4P', city: 'Ottawa' },
  { code: 'K4R', city: 'Russell' },
  { code: 'K6A', city: 'Hawkesbury' },
  { code: 'K6H', city: 'Cornwall' },
  { code: 'K6J', city: 'Cornwall' },
  { code: 'K6K', city: 'Cornwall' },
  { code: 'K6T', city: 'Brockville' },
  { code: 'K6V', city: 'Brockville' },
  { code: 'K7A', city: 'Smiths Falls' },
  { code: 'K7C', city: 'Carleton Place' },
  { code: 'K7G', city: 'Gananoque' },
  { code: 'K7H', city: 'Perth' },
  { code: 'K7K', city: 'Kingston' },
  { code: 'K7L', city: 'Kingston' },
  { code: 'K7M', city: 'Kingston' },
  { code: 'K7N', city: 'Kingston' },
  { code: 'K7P', city: 'Kingston' },
  { code: 'K7R', city: 'Napanee' },
  { code: 'K7S', city: 'Arnprior' },
  { code: 'K7V', city: 'Renfrew' },
  { code: 'K8A', city: 'Pembroke' },
  { code: 'K8B', city: 'Pembroke' },
  { code: 'K8H', city: 'Petawawa' },
  { code: 'K8N', city: 'Belleville' },
  { code: 'K8P', city: 'Belleville' },
  { code: 'K8R', city: 'Belleville' },
  { code: 'K8V', city: 'Quinte West' },
  { code: 'K9A', city: 'Cobourg' },
  { code: 'K9H', city: 'Peterborough' },
  { code: 'K9J', city: 'Peterborough' },
  { code: 'K9K', city: 'Peterborough' },
  { code: 'K9L', city: 'Peterborough' },
  { code: 'K9V', city: 'Lindsay' },
  { code: 'L0A', city: 'Millbrook' },
  { code: 'L0B', city: 'Whitby' },
  { code: 'L0C', city: 'Whitby' },
  { code: 'L0E', city: 'Keswick' },
  { code: 'L0G', city: 'Tottenham' },
  { code: 'L0H', city: 'Gormley' },
  { code: 'L0J', city: 'Kleinburg' },
  { code: 'L0K', city: 'Orillia' },
  { code: 'L0L', city: 'Barrie' },
  { code: 'L0M', city: 'Barrie' },
  { code: 'L0N', city: 'Brampton' },
  { code: 'L0P', city: 'Mississauga' },
  { code: 'L0R', city: 'Hamilton' },
  { code: 'L0S', city: 'Ridgeville' },
  { code: 'L1A', city: 'Port Hope' },
  { code: 'L1B', city: 'Newcastle' },
  { code: 'L1C', city: 'Bowmanville' },
  { code: 'L1E', city: 'Bowmanville' },
  { code: 'L1G', city: 'Oshawa' },
  { code: 'L1H', city: 'Oshawa' },
  { code: 'L1J', city: 'Oshawa' },
  { code: 'L1K', city: 'Oshawa' },
  { code: 'L1L', city: 'Oshawa' },
  { code: 'L1M', city: 'Whitby' },
  { code: 'L1N', city: 'Whitby' },
  { code: 'L1P', city: 'Whitby' },
  { code: 'L1R', city: 'Whitby' },
  { code: 'L1S', city: 'Ajax' },
  { code: 'L1T', city: 'Ajax' },
  { code: 'L1V', city: 'Pickering' },
  { code: 'L1W', city: 'Pickering' },
  { code: 'L1X', city: 'Pickering' },
  { code: 'L1Y', city: 'Pickering' },
  { code: 'L1Z', city: 'Ajax' },
  { code: 'L2A', city: 'Fort Erie' },
  { code: 'L2E', city: 'Niagara Falls' },
  { code: 'L2G', city: 'Niagara Falls' },
  { code: 'L2H', city: 'Niagara Falls' },
  { code: 'L2J', city: 'Niagara Falls' },
  { code: 'L2M', city: 'St. Catharines' },
  { code: 'L2N', city: 'St. Catharines' },
  { code: 'L2P', city: 'St. Catharines' },
  { code: 'L2R', city: 'St. Catharines' },
  { code: 'L2S', city: 'St. Catharines' },
  { code: 'L2T', city: 'St. Catharines' },
  { code: 'L2V', city: 'Thorold' },
  { code: 'L2W', city: 'St. Catharines' },
  { code: 'L3B', city: 'Welland' },
  { code: 'L3C', city: 'Welland' },
  { code: 'L3K', city: 'Port Colborne' },
  { code: 'L3M', city: 'Grimsby' },
  { code: 'L3P', city: 'Markham' },
  { code: 'L3R', city: 'Markham' },
  { code: 'L3S', city: 'Markham' },
  { code: 'L3T', city: 'Markham' },
  { code: 'L3V', city: 'Rama' },
  { code: 'L3X', city: 'Newmarket' },
  { code: 'L3Y', city: 'Newmarket' },
  { code: 'L3Z', city: 'Bradford' },
  { code: 'L4A', city: 'Whitchurch-Stouffville' },
  { code: 'L4B', city: 'Richmond Hill' },
  { code: 'L4C', city: 'Richmond Hill' },
  { code: 'L4E', city: 'Gormley' },
  { code: 'L4G', city: 'Aurora' },
  { code: 'L4H', city: 'Vaughan' },
  { code: 'L4J', city: 'Vaughan' },
  { code: 'L4K', city: 'Vaughan' },
  { code: 'L4L', city: 'Vaughan' },
  { code: 'L4M', city: 'Barrie' },
  { code: 'L4N', city: 'Barrie' },
  { code: 'L4P', city: 'Georgina' },
  { code: 'L4R', city: 'Midland' },
  { code: 'L4S', city: 'Richmond Hill' },
  { code: 'L4T', city: 'Mississauga' },
  { code: 'L4V', city: 'Mississauga' },
  { code: 'L4W', city: 'Mississauga' },
  { code: 'L4X', city: 'Mississauga' },
  { code: 'L4Y', city: 'Mississauga' },
  { code: 'L4Z', city: 'Mississauga' },
  { code: 'L5A', city: 'Mississauga' },
  { code: 'L5B', city: 'Mississauga' },
  { code: 'L5C', city: 'Mississauga' },
  { code: 'L5E', city: 'Mississauga' },
  { code: 'L5G', city: 'Mississauga' },
  { code: 'L5H', city: 'Mississauga' },
  { code: 'L5J', city: 'Mississauga' },
  { code: 'L5K', city: 'Mississauga' },
  { code: 'L5L', city: 'Mississauga' },
  { code: 'L5M', city: 'Mississauga' },
  { code: 'L5N', city: 'Mississauga' },
  { code: 'L5P', city: 'Mississauga' },
  { code: 'L5R', city: 'Mississauga' },
  { code: 'L5S', city: 'Mississauga' },
  { code: 'L5T', city: 'Mississauga' },
  { code: 'L5V', city: 'Mississauga' },
  { code: 'L5W', city: 'Mississauga' },
  { code: 'L6A', city: 'Vaughan' },
  { code: 'L6B', city: 'Markham' },
  { code: 'L6C', city: 'Markham' },
  { code: 'L6E', city: 'Markham' },
  { code: 'L6G', city: 'Markham' },
  { code: 'L6H', city: 'Oakville' },
  { code: 'L6J', city: 'Oakville' },
  { code: 'L6K', city: 'Oakville' },
  { code: 'L6L', city: 'Oakville' },
  { code: 'L6M', city: 'Oakville' },
  { code: 'L6P', city: 'Brampton' },
  { code: 'L6R', city: 'Brampton' },
  { code: 'L6S', city: 'Brampton' },
  { code: 'L6T', city: 'Brampton' },
  { code: 'L6V', city: 'Brampton' },
  { code: 'L6W', city: 'Brampton' },
  { code: 'L6X', city: 'Brampton' },
  { code: 'L6Y', city: 'Brampton' },
  { code: 'L6Z', city: 'Brampton' },
  { code: 'L7A', city: 'Brampton' },
  { code: 'L7B', city: 'King City' },
  { code: 'L7C', city: 'Caledon' },
  { code: 'L7E', city: 'Palgrave' },
  { code: 'L7G', city: 'Georgetown' },
  { code: 'L7J', city: 'Acton' },
  { code: 'L7K', city: 'Caledon' },
  { code: 'L7L', city: 'Burlington' },
  { code: 'L7M', city: 'Burlington' },
  { code: 'L7N', city: 'Burlington' },
  { code: 'L7P', city: 'Burlington' },
  { code: 'L7R', city: 'Burlington' },
  { code: 'L7S', city: 'Burlington' },
  { code: 'L7T', city: 'Burlington' },
  { code: 'L8B', city: 'Hamilton' },
  { code: 'L8E', city: 'Hamilton' },
  { code: 'L8G', city: 'Hamilton' },
  { code: 'L8H', city: 'Hamilton' },
  { code: 'L8J', city: 'Hamilton' },
  { code: 'L8K', city: 'Hamilton' },
  { code: 'L8L', city: 'Hamilton' },
  { code: 'L8M', city: 'Hamilton' },
  { code: 'L8N', city: 'Hamilton' },
  { code: 'L8P', city: 'Hamilton' },
  { code: 'L8R', city: 'Hamilton' },
  { code: 'L8S', city: 'Hamilton' },
  { code: 'L8T', city: 'Hamilton' },
  { code: 'L8V', city: 'Hamilton' },
  { code: 'L8W', city: 'Hamilton' },
  { code: 'L9A', city: 'Hamilton' },
  { code: 'L9B', city: 'Hamilton' },
  { code: 'L9C', city: 'Hamilton' },
  { code: 'L9E', city: 'Milton' },
  { code: 'L9G', city: 'Hamilton' },
  { code: 'L9H', city: 'Hamilton' },
  { code: 'L9J', city: 'Barrie' },
  { code: 'L9K', city: 'Hamilton' },
  { code: 'L9L', city: 'Port Perry' },
  { code: 'L9M', city: 'Penetanguishene' },
  { code: 'L9N', city: 'East Gwillimbury' },
  { code: 'L9P', city: 'Uxbridge' },
  { code: 'L9R', city: 'New Tecumseth' },
  { code: 'L9S', city: 'Innisfil' },
  { code: 'L9T', city: 'Milton' },
  { code: 'L9V', city: 'Orangeville' },
  { code: 'L9W', city: 'Orangeville' },
  { code: 'L9X', city: 'Minesing' },
  { code: 'L9Y', city: 'The Blue Mountains' },
  { code: 'L9Z', city: 'Wasaga Beach' },
  { code: 'M1B', city: 'Scarborough' },
  { code: 'M1C', city: 'Scarborough' },
  { code: 'M1E', city: 'Scarborough' },
  { code: 'M1G', city: 'Scarborough' },
  { code: 'M1H', city: 'Scarborough' },
  { code: 'M1J', city: 'Scarborough' },
  { code: 'M1K', city: 'Scarborough' },
  { code: 'M1L', city: 'North York' },
  { code: 'M1M', city: 'Scarborough' },
  { code: 'M1N', city: 'Scarborough' },
  { code: 'M1P', city: 'Scarborough' },
  { code: 'M1R', city: 'North York' },
  { code: 'M1S', city: 'Scarborough' },
  { code: 'M1T', city: 'Scarborough' },
  { code: 'M1V', city: 'Scarborough' },
  { code: 'M1W', city: 'Scarborough' },
  { code: 'M1X', city: 'Scarborough' },
  { code: 'M2H', city: 'North York' },
  { code: 'M2J', city: 'North York' },
  { code: 'M2K', city: 'North York' },
  { code: 'M2L', city: 'North York' },
  { code: 'M2M', city: 'North York' },
  { code: 'M2N', city: 'North York' },
  { code: 'M2P', city: 'North York' },
  { code: 'M2R', city: 'North York' },
  { code: 'M3A', city: 'North York' },
  { code: 'M3B', city: 'North York' },
  { code: 'M3C', city: 'North York' },
  { code: 'M3H', city: 'North York' },
  { code: 'M3J', city: 'North York' },
  { code: 'M3K', city: 'North York' },
  { code: 'M3L', city: 'North York' },
  { code: 'M3M', city: 'North York' },
  { code: 'M3N', city: 'North York' },
  { code: 'M4A', city: 'North York' },
  { code: 'M4B', city: 'Toronto' },
  { code: 'M4C', city: 'Toronto' },
  { code: 'M4E', city: 'Toronto' },
  { code: 'M4G', city: 'North York' },
  { code: 'M4H', city: 'Toronto' },
  { code: 'M4J', city: 'Toronto' },
  { code: 'M4K', city: 'Toronto' },
  { code: 'M4L', city: 'Old Toronto' },
  { code: 'M4M', city: 'Toronto' },
  { code: 'M4N', city: 'Toronto' },
  { code: 'M4P', city: 'North York' },
  { code: 'M4R', city: 'North York' },
  { code: 'M4S', city: 'Old Toronto' },
  { code: 'M4T', city: 'Old Toronto' },
  { code: 'M4V', city: 'Old Toronto' },
  { code: 'M4W', city: 'Old Toronto' },
  { code: 'M4X', city: 'Old Toronto' },
  { code: 'M4Y', city: 'Old Toronto' },
  { code: 'M5A', city: 'Old Toronto' },
  { code: 'M5B', city: 'Old Toronto' },
  { code: 'M5C', city: 'Old Toronto' },
  { code: 'M5E', city: 'Old Toronto' },
  { code: 'M5G', city: 'Old Toronto' },
  { code: 'M5H', city: 'Old Toronto' },
  { code: 'M5J', city: 'Toronto' },
  { code: 'M5K', city: 'Old Toronto' },
  { code: 'M5L', city: 'Old Toronto' },
  { code: 'M5M', city: 'Toronto' },
  { code: 'M5N', city: 'Old Toronto' },
  { code: 'M5P', city: 'York' },
  { code: 'M5R', city: 'Old Toronto' },
  { code: 'M5S', city: 'Old Toronto' },
  { code: 'M5T', city: 'Old Toronto' },
  { code: 'M5V', city: 'Toronto' },
  { code: 'M5W', city: 'Old Toronto' },
  { code: 'M5X', city: 'Old Toronto' },
  { code: 'M6A', city: 'North York' },
  { code: 'M6B', city: 'Toronto' },
  { code: 'M6C', city: 'Toronto' },
  { code: 'M6E', city: 'Toronto' },
  { code: 'M6G', city: 'Old Toronto' },
  { code: 'M6H', city: 'Old Toronto' },
  { code: 'M6J', city: 'Old Toronto' },
  { code: 'M6K', city: 'Old Toronto' },
  { code: 'M6L', city: 'North York' },
  { code: 'M6M', city: 'Toronto' },
  { code: 'M6N', city: 'Toronto' },
  { code: 'M6P', city: 'Toronto' },
  { code: 'M6R', city: 'Old Toronto' },
  { code: 'M6S', city: 'Toronto' },
  { code: 'M7A', city: 'North York' },
  { code: 'M7R', city: 'Mississauga' },
  { code: 'M7Y', city: 'Old Toronto' },
  { code: 'M8V', city: 'Etobicoke' },
  { code: 'M8W', city: 'Etobicoke' },
  { code: 'M8X', city: 'Etobicoke' },
  { code: 'M8Y', city: 'Etobicoke' },
  { code: 'M8Z', city: 'Etobicoke' },
  { code: 'M9A', city: 'Etobicoke' },
  { code: 'M9B', city: 'Etobicoke' },
  { code: 'M9C', city: 'Etobicoke' },
  { code: 'M9L', city: 'North York' },
  { code: 'M9M', city: 'North York' },
  { code: 'M9N', city: 'Toronto' },
  { code: 'M9P', city: 'Etobicoke' },
  { code: 'M9R', city: 'Etobicoke' },
  { code: 'M9V', city: 'Etobicoke' },
  { code: 'M9W', city: 'Etobicoke' },
  { code: 'N0A', city: 'Brantford' },
  { code: 'N0B', city: 'Kitchener' },
  { code: 'N0C', city: 'Dundalk' },
  { code: 'N0E', city: 'Brantford' },
  { code: 'N0G', city: 'Mount Forest' },
  { code: 'N0H', city: 'Owen Sound' },
  { code: 'N0J', city: 'Kitchener' },
  { code: 'N0K', city: 'Stratford' },
  { code: 'N0L', city: 'London' },
  { code: 'N0M', city: 'London' },
  { code: 'N0N', city: 'Sarnia' },
  { code: 'N0P', city: 'Windsor' },
  { code: 'N0R', city: 'Windsor' },
  { code: 'N1A', city: 'Dunnville' },
  { code: 'N1C', city: 'Guelph' },
  { code: 'N1E', city: 'Guelph' },
  { code: 'N1G', city: 'Guelph' },
  { code: 'N1H', city: 'Guelph' },
  { code: 'N1K', city: 'Guelph' },
  { code: 'N1L', city: 'Guelph' },
  { code: 'N1M', city: 'Fergus' },
  { code: 'N1P', city: 'Cambridge' },
  { code: 'N1R', city: 'Cambridge' },
  { code: 'N1S', city: 'Cambridge' },
  { code: 'N1T', city: 'Cambridge' },
  { code: 'N2A', city: 'Kitchener' },
  { code: 'N2B', city: 'Kitchener' },
  { code: 'N2C', city: 'Kitchener' },
  { code: 'N2E', city: 'Kitchener' },
  { code: 'N2G', city: 'Kitchener' },
  { code: 'N2H', city: 'Kitchener' },
  { code: 'N2J', city: 'Waterloo' },
  { code: 'N2K', city: 'Kitchener' },
  { code: 'N2L', city: 'Waterloo' },
  { code: 'N2M', city: 'Kitchener' },
  { code: 'N2N', city: 'Kitchener' },
  { code: 'N2P', city: 'Kitchener' },
  { code: 'N2R', city: 'Kitchener' },
  { code: 'N2T', city: 'Waterloo' },
  { code: 'N2V', city: 'Waterloo' },
  { code: 'N2Z', city: 'Kincardine' },
  { code: 'N3A', city: 'New Hamburg' },
  { code: 'N3B', city: 'Elmira' },
  { code: 'N3C', city: 'Cambridge' },
  { code: 'N3E', city: 'Cambridge' },
  { code: 'N3H', city: 'Cambridge' },
  { code: 'N3L', city: 'Brant' },
  { code: 'N3P', city: 'Brantford' },
  { code: 'N3R', city: 'Brantford' },
  { code: 'N3S', city: 'Brantford' },
  { code: 'N3T', city: 'Brantford' },
  { code: 'N3V', city: 'Brantford' },
  { code: 'N3W', city: 'Caledonia' },
  { code: 'N3Y', city: 'Simcoe' },
  { code: 'N4B', city: 'Delhi' },
  { code: 'N4G', city: 'Tillsonburg' },
  { code: 'N4K', city: 'Owen Sound' },
  { code: 'N4L', city: 'Meaford' },
  { code: 'N4N', city: 'Hanover' },
  { code: 'N4S', city: 'Woodstock' },
  { code: 'N4T', city: 'Woodstock' },
  { code: 'N4V', city: 'Woodstock' },
  { code: 'N4W', city: 'Listowel' },
  { code: 'N4X', city: 'Saint Marys' },
  { code: 'N4Z', city: 'Stratford' },
  { code: 'N5A', city: 'Stratford' },
  { code: 'N5C', city: 'Ingersoll' },
  { code: 'N5H', city: 'Aylmer' },
  { code: 'N5L', city: 'Port Stanley' },
  { code: 'N5P', city: 'St. Thomas' },
  { code: 'N5R', city: 'St. Thomas' },
  { code: 'N5V', city: 'London' },
  { code: 'N5W', city: 'London' },
  { code: 'N5X', city: 'London' },
  { code: 'N5Y', city: 'London' },
  { code: 'N5Z', city: 'London' },
  { code: 'N6A', city: 'London' },
  { code: 'N6B', city: 'London' },
  { code: 'N6C', city: 'London' },
  { code: 'N6E', city: 'London' },
  { code: 'N6G', city: 'London' },
  { code: 'N6H', city: 'London' },
  { code: 'N6J', city: 'London' },
  { code: 'N6K', city: 'London' },
  { code: 'N6L', city: 'London' },
  { code: 'N6M', city: 'London' },
  { code: 'N6N', city: 'London' },
  { code: 'N6P', city: 'London' },
  { code: 'N7A', city: 'Goderich' },
  { code: 'N7G', city: 'Strathroy' },
  { code: 'N7L', city: 'Chatham-Kent' },
  { code: 'N7M', city: 'Chatham-Kent' },
  { code: 'N7S', city: 'Sarnia' },
  { code: 'N7T', city: 'Sarnia' },
  { code: 'N7V', city: 'Sarnia' },
  { code: 'N7W', city: 'Sarnia' },
  { code: 'N7X', city: 'Sarnia' },
  { code: 'N8A', city: 'Wallaceburg' },
  { code: 'N8H', city: 'Leamington' },
  { code: 'N8M', city: 'Essex' },
  { code: 'N8N', city: 'Tecumseh' },
  { code: 'N8P', city: 'Tecumseh' },
  { code: 'N8R', city: 'Windsor' },
  { code: 'N8S', city: 'Windsor' },
  { code: 'N8T', city: 'Windsor' },
  { code: 'N8V', city: 'Windsor' },
  { code: 'N8W', city: 'Windsor' },
  { code: 'N8X', city: 'Windsor' },
  { code: 'N8Y', city: 'Windsor' },
  { code: 'N9A', city: 'Windsor' },
  { code: 'N9B', city: 'Windsor' },
  { code: 'N9C', city: 'Windsor' },
  { code: 'N9E', city: 'Windsor' },
  { code: 'N9G', city: 'Windsor' },
  { code: 'N9H', city: 'Windsor' },
  { code: 'N9J', city: 'Windsor' },
  { code: 'N9K', city: 'Tecumseh' },
  { code: 'N9V', city: 'Amherstburg' },
  { code: 'N9Y', city: 'Kingsville' },
  { code: 'P0A', city: 'Sundridge' },
  { code: 'P0B', city: 'Bracebridge' },
  { code: 'P0C', city: 'Bracebridge' },
  { code: 'P0E', city: 'Gravenhurst' },
  { code: 'P0G', city: 'Sudbury' },
  { code: 'P0H', city: 'North Bay' },
  { code: 'P0J', city: 'New Liskeard' },
  { code: 'P0K', city: 'Kirkland Lake' },
  { code: 'P0L', city: 'Timmins' },
  { code: 'P0M', city: 'Sudbury' },
  { code: 'P0N', city: 'Timmins' },
  { code: 'P0P', city: 'Sudbury' },
  { code: 'P0R', city: 'Sudbury' },
  { code: 'P0S', city: 'Sault Ste. Marie' },
  { code: 'P0T', city: 'Thunder Bay' },
  { code: 'P0V', city: 'Weagamow Lake' },
  { code: 'P0W', city: 'Kenora' },
  { code: 'P0X', city: 'Kenora' },
  { code: 'P0Y', city: 'Ingolf' },
  { code: 'P1A', city: 'North Bay' },
  { code: 'P1B', city: 'North Bay' },
  { code: 'P1C', city: 'North Bay' },
  { code: 'P1H', city: 'Huntsville' },
  { code: 'P1L', city: 'Bracebridge' },
  { code: 'P1P', city: 'Gravenhurst' },
  { code: 'P2A', city: 'Parry Sound' },
  { code: 'P2B', city: 'Garden Village' },
  { code: 'P2N', city: 'Kirkland Lake' },
  { code: 'P3A', city: 'Sudbury' },
  { code: 'P3B', city: 'Sudbury' },
  { code: 'P3C', city: 'Sudbury' },
  { code: 'P3E', city: 'Sudbury' },
  { code: 'P3G', city: 'Sudbury' },
  { code: 'P3L', city: 'Garson' },
  { code: 'P3N', city: 'Greater Sudbury' },
  { code: 'P3P', city: 'Hanmer' },
  { code: 'P3Y', city: 'Greater Sudbury' },
  { code: 'P4N', city: 'Timmins' },
  { code: 'P4P', city: 'Timmins' },
  { code: 'P4R', city: 'Timmins' },
  { code: 'P5A', city: 'Elliot Lake' },
  { code: 'P5E', city: 'Espanola' },
  { code: 'P5N', city: 'Kapuskasing' },
  { code: 'P6A', city: 'Sault Ste. Marie' },
  { code: 'P6B', city: 'Sault Ste. Marie' },
  { code: 'P6C', city: 'Sault Ste. Marie' },
  { code: 'P7A', city: 'Thunder Bay' },
  { code: 'P7B', city: 'Thunder Bay' },
  { code: 'P7C', city: 'Thunder Bay' },
  { code: 'P7E', city: 'Thunder Bay' },
  { code: 'P7G', city: 'Thunder Bay' },
  { code: 'P7J', city: 'Thunder Bay' },
  { code: 'P7K', city: 'Thunder Bay' },
  { code: 'P7L', city: 'Neebing' },
  { code: 'P8N', city: 'Dryden' },
  { code: 'P8T', city: 'Sioux Lookout' },
  { code: 'P9A', city: 'Fort Frances' },
  { code: 'P9N', city: 'Kenora' },
]

const FSA_BY_CODE = new Map(POSTAL_FSA_LOCATIONS.map((item) => [item.code, item]))

export const POSTAL_FSA_CODES = new Set(POSTAL_FSA_LOCATIONS.map((item) => item.code))

export function formatFsaLabel(code: string): string {
  const item = FSA_BY_CODE.get(code.toUpperCase())
  if (!item) return code
  return `${item.code} — ${item.city}`
}

export function resolveFsaLocation(code: string): PostalFsaLocation | null {
  return FSA_BY_CODE.get(code.toUpperCase()) ?? null
}

export function isValidFsaCode(code: string): boolean {
  return POSTAL_FSA_CODES.has(code.toUpperCase())
}
