-- Migration: Import task templates data
-- Generated from: src/core/mock-data/task-templates.json
-- Total templates: 206
-- Date: 2025-12-06

INSERT INTO `fw_task_templates`
  (`name`, `category`, `duration_days`, `start_offset_days`, `end_offset_days`, `milestone`, `status`, `notes`, `wbs_path`, `task_order`)
VALUES
  ('Client Business Planning Meeting 1', 'Planning & Design', 3, 0, NULL, 'meeting', 'planned', NULL, NULL, 1),
  ('Client Business Planning Meeting 2', 'Planning & Design', 3, 3, NULL, 'meeting', 'planned', NULL, NULL, 2),
  ('Client Business Planning Meeting 3', 'Planning & Design', 3, 6, NULL, 'meeting', 'Planned', NULL, NULL, 3),
  ('Client Business Planning Meeting 4', 'Planning & Design', 3, 9, NULL, 'meeting', 'Planned', NULL, NULL, 4),
  ('Client Business Planning Meeting 5', 'Planning & Design', 3, 12, NULL, 'meeting', 'Planned', NULL, NULL, 5),
  ('Space Review 1', 'Planning & Design', 3, 15, NULL, 'review', 'Planned', NULL, NULL, 6),
  ('Space Review 2', 'Planning & Design', 3, 18, NULL, 'review', 'Planned', NULL, NULL, 7),
  ('Space Review 3', 'Planning & Design', 3, 21, NULL, 'review', 'Planned', NULL, NULL, 8),
  ('Space Review 4', 'Planning & Design', 3, 24, NULL, 'review', 'Planned', NULL, NULL, 9),
  ('Space Review 5', 'Planning & Design', 3, 27, NULL, 'review', 'Planned', NULL, NULL, 10),
  ('Business Pro-Forma 1', 'Planning & Design', 5, 30, NULL, NULL, 'Planned', NULL, NULL, 11),
  ('Business Pro-Forma 2', 'Planning & Design', 5, 35, NULL, NULL, 'Planned', NULL, NULL, 12),
  ('Business Pro-Forma 3', 'Planning & Design', 5, 40, NULL, NULL, 'Planned', NULL, NULL, 13),
  ('Architectural Concept Meeting', 'Planning & Design', 4, 45, NULL, 'meeting', 'Planned', NULL, NULL, 14),
  ('Architectural Client Meeting One', 'Planning & Design', 4, 49, NULL, 'meeting', 'Planned', NULL, NULL, 15),
  ('Architectural Client Meeting Two', 'Planning & Design', 4, 53, NULL, 'meeting', 'Planned', NULL, NULL, 16),
  ('Architectural Client Meeting Three', 'Planning & Design', 4, 57, NULL, 'meeting', 'Planned', NULL, NULL, 17),
  ('Design Concept Client Meeting One', 'Planning & Design', 4, 61, NULL, 'meeting', 'Planned', NULL, NULL, 18),
  ('Design Concept Client Meeting Two', 'Planning & Design', 4, 65, NULL, 'meeting', 'Planned', NULL, NULL, 19),
  ('Design Concept Client Meeting Three', 'Planning & Design', 4, 69, NULL, 'meeting', 'Planned', NULL, NULL, 20),
  ('Submission of Architectural Drawings', 'Planning & Design', 8, 73, NULL, NULL, 'Planned', NULL, NULL, 21),
  ('Brand Meeting With Clients', 'Planning & Design', NULL, NULL, NULL, 'meeting', 'Planned', NULL, NULL, 22),
  ('Attain Sign & Window Decal Quote', 'Materials & Ordering', NULL, NULL, NULL, NULL, 'Planned', NULL, NULL, 23),
  ('Signage Installation', 'Branding & Signage', NULL, NULL, NULL, NULL, 'Planned', NULL, NULL, 24),
  ('Create Full Schedule Of Materials List To Order', 'Materials & Ordering', NULL, NULL, NULL, NULL, 'Planned', NULL, NULL, 25),
  ('Meeting with Clients On Material List', 'Planning & Design', NULL, NULL, NULL, 'meeting', 'Planned', NULL, NULL, 26),
  ('Sign Off On Materials List', 'Permits & Approvals', NULL, NULL, NULL, 'approval', 'Planned', NULL, NULL, 27),
  ('Purchase All Materials', 'Materials & Ordering', NULL, NULL, NULL, NULL, 'Planned', NULL, NULL, 28),
  ('Payment of City Permit Fee’s', 'Permits & Approvals', 1, 88, NULL, NULL, 'Planned', NULL, NULL, 29),
  ('Approved Permit Application', 'Permits & Approvals', 1, 89, NULL, NULL, 'Planned', NULL, NULL, 30),
  ('Demolition Of Space', 'Demolition & Site Prep', NULL, NULL, NULL, NULL, 'Planned', NULL, NULL, 31),
  ('Order Construction Bin One', 'Demolition & Site Prep', 1, 91, NULL, NULL, 'Planned', NULL, NULL, 32),
  ('Order Construction Bin Two', 'Demolition & Site Prep', 1, 92, NULL, NULL, 'Planned', NULL, NULL, 33),
  ('Order Construction Bin Three', 'Demolition & Site Prep', 1, 93, NULL, NULL, 'Planned', NULL, NULL, 34),
  ('Order Construction Bin Four', 'Demolition & Site Prep', 1, 94, NULL, NULL, 'Planned', NULL, NULL, 35),
  ('Order Construction Bin Five', 'Demolition & Site Prep', 1, 95, NULL, NULL, 'Planned', NULL, NULL, 36),
  ('Pick Up Construction Bin', 'Demolition & Site Prep', 1, 96, NULL, NULL, 'Planned', NULL, NULL, 37),
  ('Pick Up Construction Bin', 'Demolition & Site Prep', 1, 97, NULL, NULL, 'Planned', NULL, NULL, 38),
  ('Pick Up Construction Bin', 'Demolition & Site Prep', 1, 98, NULL, NULL, 'Planned', NULL, NULL, 39),
  ('Pick Up Construction Bin', 'Demolition & Site Prep', 1, 99, NULL, NULL, 'Planned', NULL, NULL, 40),
  ('Pick Up Construction Bin', 'Demolition & Site Prep', 1, 100, NULL, NULL, 'Planned', NULL, NULL, 41),
  ('Order Concrete Bin', 'Demolition & Site Prep', 1, 101, NULL, NULL, 'Planned', NULL, NULL, 42),
  ('Pick Up Concrete Bin', 'Demolition & Site Prep', 1, 102, NULL, NULL, 'Planned', NULL, NULL, 43),
  ('Order Dirt Bin', 'Demolition & Site Prep', 1, 103, NULL, NULL, 'Planned', NULL, NULL, 44),
  ('Pick Up Dirt Bin', 'Demolition & Site Prep', 1, 104, NULL, NULL, 'Planned', NULL, NULL, 45),
  ('Order Storage Bin', 'Demolition & Site Prep', 1, 105, NULL, NULL, 'Planned', NULL, NULL, 46),
  ('Pick Up Storage Bin', 'Demolition & Site Prep', 1, 106, NULL, NULL, 'Planned', NULL, NULL, 47),
  ('Create The Network Plan', 'Network & IT', NULL, NULL, NULL, NULL, 'Planned', NULL, NULL, 48),
  ('Client To Sign Off On Network Plan', 'Permits & Approvals', NULL, NULL, NULL, 'approval', 'Planned', NULL, NULL, 49),
  ('Schedule Installation of Network Lines', 'Network & IT', NULL, NULL, NULL, NULL, 'Planned', NULL, NULL, 50),
  ('Install Network Lines', 'Network & IT', NULL, NULL, NULL, NULL, 'Planned', NULL, NULL, 51),
  ('Roofing Flashing Site Visit', 'Roofing', NULL, NULL, NULL, 'visit', 'Planned', NULL, NULL, 52),
  ('Schedule Roofing Flashing', 'Roofing', NULL, NULL, NULL, NULL, 'Planned', NULL, NULL, 53),
  ('Roofing Flashing', 'Roofing', NULL, NULL, NULL, NULL, 'Planned', NULL, NULL, 54),
  ('Schedule Initial HVAC Pre-Start Site Visit & Inspection', 'HVAC', 1, 114, NULL, 'inspection', 'Planned', NULL, NULL, 55),
  ('HVAC Pre-Inspection', 'HVAC', 4, 115, NULL, 'inspection', 'Planned', NULL, NULL, 56),
  ('Schedule HVAC Rough In', 'HVAC', 1, 119, NULL, NULL, 'Planned', NULL, NULL, 57),
  ('HVAC Rough In', 'HVAC', NULL, NULL, NULL, NULL, 'Planned', NULL, NULL, 58),
  ('Schedule HVAC Rough-In Inspections', 'HVAC', 1, 121, NULL, 'inspection', 'Planned', NULL, NULL, 59),
  ('HVAC Rough In Inspection', 'HVAC', 6, 122, NULL, 'inspection', 'Planned', NULL, NULL, 60),
  ('Schedule HVAC Finish', 'HVAC', 1, 128, NULL, NULL, 'Planned', NULL, NULL, 61),
  ('HAVAC Finish', 'HVAC', NULL, NULL, NULL, NULL, 'Planned', NULL, NULL, 62),
  ('Schedule HVAC Final Inspections', 'HVAC', 1, 130, NULL, 'inspection', 'Planned', NULL, NULL, 63),
  ('HVAC Final Inspection', 'HVAC', 6, 131, NULL, 'inspection', 'Planned', NULL, NULL, 64),
  ('"Schedule Concrete Coring, Cutting & Removal"', 'Demolition & Site Prep', 1, 137, NULL, NULL, 'Planned', NULL, NULL, 65),
  ('"Concrete Coring, Cutting Site Visit"', 'Demolition & Site Prep', 4, 138, NULL, 'visit', 'Planned', NULL, NULL, 66),
  ('"Concrete Coring, Cutting & Removal"', 'Demolition & Site Prep', NULL, NULL, NULL, NULL, 'Planned', NULL, NULL, 67),
  ('Schedule Concrete Re-Fill', 'Demolition & Site Prep', 1, 143, NULL, NULL, 'Planned', NULL, NULL, 68),
  ('Concrete Re-Fill', 'Demolition & Site Prep', NULL, NULL, NULL, NULL, 'Planned', NULL, NULL, 69),
  ('Schedule Initial Plumbing Pre-Start Site Visit & Inspection', 'Demolition & Site Prep', 4, 145, NULL, 'inspection', 'Planned', NULL, NULL, 70),
  ('Plumbing Marking & Cut Lines', 'Demolition & Site Prep', NULL, NULL, NULL, NULL, 'Planned', NULL, NULL, 71),
  ('Schedule Plumbing Underground Rough In', 'Demolition & Site Prep', 1, 150, NULL, NULL, 'Planned', NULL, NULL, 72),
  ('Plumbing Underground Rough In', 'Demolition & Site Prep', NULL, NULL, NULL, NULL, 'Planned', NULL, NULL, 73),
  ('Schedule Plumbing Underground Rough-In Inspections', 'Demolition & Site Prep', 6, 152, NULL, 'inspection', 'Planned', NULL, NULL, 74),
  ('Schedule Backfill of Underground Rough-In', 'Other', 1, 158, NULL, NULL, 'Planned', NULL, NULL, 75),
  ('Backfill Trenches', 'Other', NULL, NULL, NULL, NULL, 'Planned', NULL, NULL, 76),
  ('Schedule Plumbing Above Ground Rough In', 'Demolition & Site Prep', 1, 160, NULL, NULL, 'Planned', NULL, NULL, 77),
  ('Plumbing Above Ground Rough In', 'Demolition & Site Prep', NULL, NULL, NULL, NULL, 'Planned', NULL, NULL, 78),
  ('Schedule Plumbing Above Ground Rough-In Inspections', 'Demolition & Site Prep', 6, 162, NULL, 'inspection', 'Planned', NULL, NULL, 79),
  ('Schedule Final Plumbing Work Pre-Start Meeting', 'Planning & Design', 1, 168, NULL, 'meeting', 'Planned', NULL, NULL, 80),
  ('Final Plumbing Site Visit', 'Demolition & Site Prep', 4, 169, NULL, 'visit', 'Planned', NULL, NULL, 81),
  ('Finish Plumbing Fixtures', 'Demolition & Site Prep', NULL, NULL, NULL, NULL, 'Planned', NULL, NULL, 82),
  ('Schedule Plumbing Final', 'Demolition & Site Prep', 1, 174, NULL, NULL, 'Planned', NULL, NULL, 83),
  ('Plumbing Final inspections', 'Demolition & Site Prep', NULL, NULL, NULL, 'inspection', 'Planned', NULL, NULL, 84),
  ('Schedule Sprinkler System Review Meeting(s)', 'Planning & Design', 1, 176, NULL, 'meeting', 'Planned', NULL, NULL, 85),
  ('Sprinkler System Review Meeting(s)', 'Planning & Design', 4, 177, NULL, 'meeting', 'Planned', NULL, NULL, 86),
  ('Get Sprinkler Quote(s)', 'Sprinkler', 2, 181, NULL, NULL, 'Planned', NULL, NULL, 87),
  ('Schedule Sprinkler Rough In', 'Sprinkler', 1, 183, NULL, NULL, 'Planned', NULL, NULL, 88),
  ('Complete Sprinkler Rough In', 'Sprinkler', NULL, NULL, NULL, NULL, 'Planned', NULL, NULL, 89),
  ('Schedule Sprinkler Completion Work', 'Sprinkler', 1, 185, NULL, NULL, 'Planned', NULL, NULL, 90),
  ('Complete Sprinkler Final', 'Sprinkler', NULL, NULL, NULL, NULL, 'Planned', NULL, NULL, 91),
  ('Schedule Sprinkler Inspection', 'Sprinkler', 6, 187, NULL, 'inspection', 'Planned', NULL, NULL, 92),
  ('Schedule Initial Electrical Pre-Start Site Visit & Inspection', 'Electrical', NULL, NULL, NULL, 'inspection', 'Planned', NULL, NULL, 93),
  ('Schedule Review of Electrical Rough-Ins', 'Planning & Design', NULL, NULL, NULL, 'review', 'Planned', NULL, NULL, 94),
  ('Schedule Electrical Rough-Ins', 'Electrical', NULL, NULL, NULL, NULL, 'Planned', NULL, NULL, 95),
  ('Electrical Rough-In’s', 'Electrical', NULL, NULL, NULL, NULL, 'Planned', NULL, NULL, 96),
  ('Schedule Electrical Finish Post Drywall', 'Electrical', NULL, NULL, NULL, NULL, 'Planned', NULL, NULL, 97),
  ('Electrical Finish Post Drywall', 'Electrical', NULL, NULL, NULL, NULL, 'Planned', NULL, NULL, 98),
  ('Schedule Electrical Finish Post Cabinets', 'Demolition & Site Prep', NULL, NULL, NULL, NULL, 'Planned', NULL, NULL, 99),
  ('Electrical Finish Post Cabinets', 'Demolition & Site Prep', NULL, NULL, NULL, NULL, 'Planned', NULL, NULL, 100),
  ('Schedule Electrical Finish', 'Electrical', NULL, NULL, NULL, NULL, 'Planned', NULL, NULL, 101),
  ('Full Electrical Finish', 'Electrical', NULL, NULL, NULL, NULL, 'Planned', NULL, NULL, 102),
  ('Attain Electoral ESA Permit Final', 'Permits & Approvals', NULL, NULL, NULL, NULL, 'planned', NULL, NULL, 103),
  ('Schedule Framing Initial Site Visit', 'Framing & Structure', NULL, NULL, NULL, 'visit', 'Planned', NULL, NULL, 104),
  ('Schedule Framing', 'Framing & Structure', NULL, NULL, NULL, NULL, 'Planned', NULL, NULL, 105),
  ('Framing', 'Framing & Structure', NULL, NULL, NULL, NULL, 'Planned', NULL, NULL, 106),
  ('Install Framing Strengthening', 'Framing & Structure', NULL, NULL, NULL, NULL, 'Planned', NULL, NULL, 107),
  ('Install Insulation', 'Framing & Structure', NULL, NULL, NULL, NULL, 'Planned', NULL, NULL, 108),
  ('Schedule Rough In Door Operators', 'Framing & Structure', 4, 209, NULL, NULL, 'Planned', NULL, NULL, 109),
  ('Door Operator Rough In', 'Framing & Structure', NULL, NULL, NULL, NULL, 'Planned', NULL, NULL, 110),
  ('Schedule Drywall', 'Drywall', NULL, NULL, NULL, NULL, 'Planned', NULL, NULL, 111),
  ('Drywall Install', 'Drywall', NULL, NULL, NULL, NULL, 'Planned', NULL, NULL, 112),
  ('Schedule Taping', 'Drywall', NULL, NULL, NULL, NULL, 'Planned', NULL, NULL, 113),
  ('Taping', 'Drywall', NULL, NULL, NULL, NULL, 'Planned', NULL, NULL, 114),
  ('Schedule Paint Scope of Work', 'Painting', 2, 218, NULL, NULL, 'Planned', NULL, NULL, 115),
  ('Paint Scope of Work Meeting', 'Planning & Design', 4, 220, NULL, 'meeting', 'Planned', NULL, NULL, 116),
  ('Schedule Paint Priming', 'Painting', 1, 224, NULL, NULL, 'Planned', NULL, NULL, 117),
  ('Schedule Paint Coat 1', 'Painting', 1, 225, NULL, NULL, 'Planned', NULL, NULL, 118),
  ('Schedule Paint Coat 2', 'Painting', 1, 226, NULL, NULL, 'Planned', NULL, NULL, 119),
  ('Schedule Paint Coat 3', 'Painting', 1, 227, NULL, NULL, 'Planned', NULL, NULL, 120),
  ('Schedule Paint Final', 'Painting', 1, 228, NULL, NULL, 'Planned', NULL, NULL, 121),
  ('Schedule Epoxy Paint Work', 'Painting', 1, 229, NULL, NULL, 'Planned', NULL, NULL, 122),
  ('Paint Coat 1', 'Painting', NULL, NULL, NULL, NULL, 'Planned', NULL, NULL, 123),
  ('Paint Coat 2', 'Painting', NULL, NULL, NULL, NULL, 'Planned', NULL, NULL, 124),
  ('Paint Coat 3', 'Painting', NULL, NULL, NULL, NULL, 'Planned', NULL, NULL, 125),
  ('Paint Final', 'Painting', NULL, NULL, NULL, NULL, 'Planned', NULL, NULL, 126),
  ('Epoxy Painting', 'Painting', NULL, NULL, NULL, NULL, 'Planned', NULL, NULL, 127),
  ('Create Preliminary Millwork Drawings', 'Planning & Design', NULL, NULL, NULL, NULL, 'Planned', NULL, NULL, 128),
  ('Schedule Meeting with Clients To Review Millwork Drawings', 'Planning & Design', NULL, NULL, NULL, 'meeting', 'Planned', NULL, NULL, 129),
  ('Clients Must Sign Off On Millwork Drawings', 'Planning & Design', NULL, NULL, NULL, 'approval', 'Planned', NULL, NULL, 130),
  ('Put Millwork into Production', 'Millwork', NULL, NULL, NULL, NULL, 'Planned', NULL, NULL, 131),
  ('Schedule Millwork Install', 'Millwork', NULL, NULL, NULL, NULL, 'Planned', NULL, NULL, 132),
  ('Installation of Millwork', 'Millwork', NULL, NULL, NULL, NULL, 'Planned', NULL, NULL, 133),
  ('Order All Doors & Hardware', 'Doors & Hardware', 8, 241, NULL, NULL, 'Planned', NULL, NULL, 134),
  ('Materials Site Visit Check', 'Materials & Ordering', 4, 249, NULL, 'visit', 'Planned', NULL, NULL, 135),
  ('Schedule Door Frame Installation', 'Doors & Hardware', 2, 253, NULL, NULL, 'Planned', NULL, NULL, 136),
  ('Door Frame Installation', 'Doors & Hardware', NULL, NULL, NULL, NULL, 'planned', NULL, NULL, 137),
  ('Schedule Door Installation', 'Doors & Hardware', 1, 256, NULL, NULL, 'Planned', NULL, NULL, 138),
  ('Door Installation', 'Doors & Hardware', NULL, NULL, NULL, NULL, 'planned', NULL, NULL, 139),
  ('Schedule Door Hardware Installation', 'Doors & Hardware', 1, 258, NULL, NULL, 'Planned', NULL, NULL, 140),
  ('Door Hardware Installation (including Nubs)', 'Doors & Hardware', NULL, NULL, NULL, NULL, 'planned', NULL, NULL, 141),
  ('Get Quote For Security Gate', 'Doors & Hardware', 1, 260, NULL, NULL, 'Planned', NULL, NULL, 142),
  ('Approve Security Gate Drawing', 'Planning & Design', 4, 261, NULL, NULL, 'Planned', NULL, NULL, 143),
  ('Schedule Security Gate On-Site Measurements', 'Doors & Hardware', 1, 265, NULL, NULL, 'Planned', NULL, NULL, 144),
  ('Schedule Security Gate Install', 'Doors & Hardware', 1, 266, NULL, NULL, 'Planned', NULL, NULL, 145),
  ('Order Ceiling Grid Materials', 'Ceiling', 4, 267, NULL, NULL, 'Planned', NULL, NULL, 146),
  ('Order Ceiling Tiles', 'Ceiling', 4, 271, NULL, NULL, 'Planned', NULL, NULL, 147),
  ('Schedule Ceiling Grid Work', 'Ceiling', 1, 275, NULL, NULL, 'Planned', NULL, NULL, 148),
  ('Schedule Ceiling Tile Work', 'Ceiling', 1, 276, NULL, NULL, 'Planned', NULL, NULL, 149),
  ('Ceiling Grid Install', 'Ceiling', NULL, NULL, NULL, NULL, 'Planned', NULL, NULL, 150),
  ('Ceiling Tile Install', 'Ceiling', NULL, NULL, NULL, NULL, 'Planned', NULL, NULL, 151),
  ('Order All Vinyl  Flooring', 'Flooring', 8, 279, NULL, NULL, 'Planned', NULL, NULL, 152),
  ('Order All Tile Flooring & Wall Applications', 'Flooring', 8, 287, NULL, NULL, 'Planned', NULL, NULL, 153),
  ('Order All Wood or Other Flooring', 'Flooring', 8, 295, NULL, NULL, 'Planned', NULL, NULL, 154),
  ('Order All Vinyl Glue', 'Flooring', 4, 303, NULL, NULL, 'Planned', NULL, NULL, 155),
  ('Order All Mortar & Trim', 'Flooring', 4, 307, NULL, NULL, 'Planned', NULL, NULL, 156),
  ('Order All Sub Materials & Glue', 'Materials & Ordering', 4, 311, NULL, NULL, 'Planned', NULL, NULL, 157),
  ('Order All Transition Pieces', 'Flooring', 2, 315, NULL, NULL, 'Planned', NULL, NULL, 158),
  ('Order Any Epoxy Materials', 'Painting', 2, 317, NULL, NULL, 'Planned', NULL, NULL, 159),
  ('Flooring On Site Visit Tile', 'Flooring', 4, 319, NULL, 'visit', 'Planned', NULL, NULL, 160),
  ('Flooring On Site Visit Vinyl', 'Flooring', 4, 323, NULL, 'visit', 'Planned', NULL, NULL, 161),
  ('Schedule All Vinyl Flooring', 'Flooring', 4, 327, NULL, NULL, 'Planned', NULL, NULL, 162),
  ('Schedule All Tile Flooring', 'Flooring', 4, 331, NULL, NULL, 'Planned', NULL, NULL, 163),
  ('Schedule All Wood or Other Flooring', 'Flooring', 2, 335, NULL, NULL, 'Planned', NULL, NULL, 164),
  ('Schedule All Vinyl Glue', 'Flooring', 2, 337, NULL, NULL, 'Planned', NULL, NULL, 165),
  ('Schedule All Mortar & Trim', 'Flooring', 2, 339, NULL, NULL, 'Planned', NULL, NULL, 166),
  ('Schedule All Sub Materials & Glue', 'Materials & Ordering', 2, 341, NULL, NULL, 'Planned', NULL, NULL, 167),
  ('Schedule All Transition Piece Work', 'Flooring', 2, 343, NULL, NULL, 'Planned', NULL, NULL, 168),
  ('Schedule Floor Prep Work', 'Other', 2, 345, NULL, NULL, 'Planned', NULL, NULL, 169),
  ('Schedule Epoxy Floor Work', 'Painting', 2, 347, NULL, NULL, 'Planned', NULL, NULL, 170),
  ('Floor & Wall Tiling Install', 'Other', NULL, NULL, NULL, NULL, 'Planned', NULL, NULL, 171),
  ('Vinyl Flooring Install', 'Flooring', NULL, NULL, NULL, NULL, 'Planned', NULL, NULL, 172),
  ('Wood or Other Flooring Install', 'Flooring', NULL, NULL, NULL, NULL, 'Planned', NULL, NULL, 173),
  ('Epoxy Floor Install', 'Painting', NULL, NULL, NULL, NULL, 'Planned', NULL, NULL, 174),
  ('Floor Prep Work', 'Other', NULL, NULL, NULL, NULL, 'Planned', NULL, NULL, 175),
  ('Order Barrier Free Equipment', 'Fixtures & Equipment', 1, 354, NULL, NULL, 'Planned', NULL, NULL, 176),
  ('Order Bathroom Fixtures', 'Fixtures & Equipment', 2, 355, NULL, NULL, 'Planned', NULL, NULL, 177),
  ('Order Plumbing Fixtures', 'Demolition & Site Prep', 2, 357, NULL, NULL, 'Planned', NULL, NULL, 178),
  ('Schedule Barrier Free Equipment Install', 'Fixtures & Equipment', 1, 359, NULL, NULL, 'Planned', NULL, NULL, 179),
  ('Barrie Free Equipment Install', 'Fixtures & Equipment', NULL, NULL, NULL, NULL, 'Planned', NULL, NULL, 180),
  ('Schedule Bathroom (non-plumbing) Fixtures Install', 'Demolition & Site Prep', 1, 361, NULL, NULL, 'Planned', NULL, NULL, 181),
  ('Bathroom (non-plumbing) Fixtures Install', 'Demolition & Site Prep', NULL, NULL, NULL, NULL, 'planned', NULL, NULL, 182),
  ('Schedule Trim Work', 'Finishing', NULL, NULL, NULL, NULL, 'Planned', NULL, NULL, 183),
  ('Trim Work Install', 'Finishing', NULL, NULL, NULL, NULL, 'Planned', NULL, NULL, 184),
  ('Order Door Numbers', 'Doors & Hardware', NULL, NULL, NULL, NULL, 'Planned', NULL, NULL, 185),
  ('Schedule Install of Door Numbers', 'Doors & Hardware', NULL, NULL, NULL, NULL, 'Planned', NULL, NULL, 186),
  ('Installation of Door Numbers', 'Doors & Hardware', NULL, NULL, NULL, NULL, 'Planned', NULL, NULL, 187),
  ('Order Wallpaper', 'Finishing', NULL, NULL, NULL, NULL, 'Planned', NULL, NULL, 188),
  ('Schedule Install of Wallpaper', 'Finishing', NULL, NULL, NULL, NULL, 'Planned', NULL, NULL, 189),
  ('Installation of Wallpaper', 'Finishing', NULL, NULL, NULL, NULL, 'Planned', NULL, NULL, 190),
  ('Schedule Site Visit For Stone Work', 'Finishing', NULL, NULL, NULL, 'visit', 'Planned', NULL, NULL, 191),
  ('Installation of Stonework', 'Finishing', NULL, NULL, NULL, NULL, 'Planned', NULL, NULL, 192),
  ('Order Blinds', 'Finishing', NULL, NULL, NULL, NULL, 'Planned', NULL, NULL, 193),
  ('Schedule Installation of Blinds', 'Finishing', NULL, NULL, NULL, NULL, 'Planned', NULL, NULL, 194),
  ('Installation of Blinds', 'Finishing', NULL, NULL, NULL, NULL, 'Planned', NULL, NULL, 195),
  ('Order Baseboard Materials', 'Finishing', 4, 376, NULL, NULL, 'Planned', NULL, NULL, 196),
  ('Schedule Baseboard Installation', 'Finishing', 1, 380, NULL, NULL, 'Planned', NULL, NULL, 197),
  ('Install Baseboard(s)', 'Finishing', NULL, NULL, NULL, NULL, 'Planned', NULL, NULL, 198),
  ('Order Trim Material', 'Finishing', 4, 382, NULL, NULL, 'Planned', NULL, NULL, 199),
  ('Schedule Trim Work', 'Finishing', 1, 386, NULL, NULL, 'Planned', NULL, NULL, 200),
  ('Install Trim', 'Finishing', NULL, NULL, NULL, NULL, 'Planned', NULL, NULL, 201),
  ('Schedule Finish Door Operators', 'Framing & Structure', 1, 388, NULL, NULL, 'Planned', NULL, NULL, 202),
  ('Door Operator Finish Completion', 'Framing & Structure', NULL, NULL, NULL, NULL, 'planned', NULL, NULL, 203),
  ('Install Door Closer(s)', 'Doors & Hardware', NULL, NULL, NULL, NULL, 'Planned', NULL, NULL, 204),
  ('Commercial Clean Full Space One', 'Cleaning', 4, 391, NULL, NULL, 'Planned', NULL, NULL, 205),
  ('Commercial Clean Full Space Final', 'Cleaning', 4, 395, NULL, NULL, 'Planned', NULL, NULL, 206);

-- Verify import
SELECT COUNT(*) as imported_count FROM `fw_task_templates`;
-- Expected: 206
